### ISSUE TITLE
Console issues

### ISSUE THREAD

**Issue by patrickkusebauch** [dbrumann/deptrac#49]
- `InitCommand` references `example_configuration.yml` but the path to it seems to be incorrect.
- `DebugTokenCommand` - if we set the default `$tokenType` here already, we do not need to work with `null` deeper in. Especially by the time we get to `LayerForTokenAnalyser`, I would recommend not allowing `null` for the `$tokenType`
- `AnalyseCommand` - uses `AnalyseException` internally (not exposed to end-user writing extension), but is not taken advantage of. I think it would be easier if `AnalyseRunner::run` just returned `bool` instead of `void`. Or am I missing something there?
- `SymfonyOutput` should IMHO not be internal as it will be used by people writing new Commands

**Comment by dbrumann** [comment]
> InitCommand

Yes, the locations have changed. I will move the template file into the config/ directory and pass it to Dumper as a constructor argument instead. That should solve the issue and also make the template exchangeable.

> DebugTokenCommand ...

Good idea. I was originally trying to return what kind of token we have in the output, but it doesn't make much sense anyway, so now it can be simplified.

> AnalyseCommand ...

I think we should keep the exception, but print an error message instead of just having the return code be 1. Having a bool only allows us to say if something went wrong, but we won't be able to tell what exactly.

> SymfonyOutput should IMHO not be internal as it will be used by people writing new Commands

Right now, there is some inconsistency with the output objects. If I remember correctly the underlying Symfony Output leaks into some commands/formatters, which makes the point of these object less useful. I have to replace the LegacyResult in the formatters anyway, so I will probably leave this as is for now and fix it later.
