### ISSUE TITLE
General notes

### ISSUE THREAD

**Issue by patrickkusebauch** [dbrumann/deptrac#50]
- There is a lot of duplicity/simplification we can do in `Analyser`, but that can wait once we merge it.
- I am a bit confused with the directory structure. Some of it is oriented around domains (Analyser, Ast) others by the technical implementation (Exceptions, Subscriber). It would be nice to have it one way or the other. (I prefer domains personally)
- For extending, it would be nice to have one folder with all the extension points (interfaces, events to hook into, public API classes etc.)

It is a monumental refactor, awesome job on your part. I think we should merge it ASAP and we can clean up after the fact.

**Comment by dbrumann** [comment]
> There is a lot of duplicity/simplification we can do in Analyser, but that can wait once we merge it.

Yes, same for commands. The PR is big enough already. I'd much rather do follow up-PRs in the future.

> I am a bit confused with the directory structure. Some of it is oriented around domains (Analyser, Ast) others by the technical implementation (Exceptions, Subscriber). It would be nice to have it one way or the other. (I prefer domains personally)

This was intentional, as I prefer having events, subscribers and exceptions at root level to better see all of them at a glance. That makes it easier to see if there already is one that fits or can be adjusted to a new use case. It also avoids duplication just to not "contaminate" the domain, which is not really an issue here, because I don't want to split them into separate packages anyway.

For events/subscribers it is rather inconsistent right now, so I might as well move them into their respective area. The exceptions I would like to leave for now. I am planning an overhaul of the exception handling anyway to avoid global exceptions like InvalidArgumentException and also have clearer messages, which help locate where the problem is, i.e. avoid using ShouldNotHappenException.

> For extending, it would be nice to have one folder with all the extension points (interfaces, events to hook into, public API classes etc.)

Yes this is what I'm going for, either have a dedicated directory or even better a separate repository, e.g. deptrac-contracts, which extensions can use as dependency. That way, you don't need to require the whole source when writing an extension, but otherwise using the phar archive. That will be a follow up, though. I want to make some other adjustments first, namely remove methods like getAlias from the interface in favor of using tag attributes in the container (like we do for collectors) and also remove usage of the LegacyResult in the output formatters.
